### ISSUE TITLE
Gmail not working

### ISSUE THREAD

**Issue by mustafapc19** [sonnyp/gigagram#12]
Using the default url just signs me in a google account settings(privacy etc.). But if I change the url to "https://mail.google.com/mail/u/0/#inbox" everything is okay. Can anyone else test this issue and confirm?

**Comment by sonnyp** [comment]
I confirm. Could you send a PR?

**Comment by sonnyp** [comment]
https://github.com/sonnyp/gigagram/commit/a7e1b32ca49c6bee5a7ecee4437f2fc58e409ba5
