### ISSUE TITLE
A detach button

### ISSUE THREAD

**Issue by mustafapc19** [sonnyp/gigagram#15]
I know this might be a little complicated. 
Like if a user detaches an app. It should have .desktop app. But when user re-attaches it. It should delete the .desktop file.
And should the app allow tab creation for individual .desktop app. It could be really helpful for app like Google Doc(Gsuite in general).

**Comment by sonnyp** [comment]
:+1:  See our previous conversation https://github.com/sonnyp/gigagram/issues/6#issuecomment-511124624

**Comment by sonnyp** [comment]
https://github.com/sonnyp/gigagram/pull/19 work in progress

**Comment by sonnyp** [comment]
closing in favor of https://github.com/sonnyp/gigagram/issues/21

**Comment by sonnyp** [comment]
detach menu item is now in master
