### ISSUE TITLE
Force refresh button

### ISSUE THREAD

**Issue by codyfish** [sonnyp/gigagram#17]
When adding custom services, I need to restart the app. I did also try to use reddit and had to restart it a few times. A force reload button or similar would be usefull

Edit: 
It seems to depend on the website whether a restart is required. Instagram and reddit needed one, tiny rss didn't. I really appreciate your work.

**Comment by sonnyp** [comment]
I'd rather fix the reason you have to refresh in the first place. Any idea? Do you also have to refresh in GNOME Web/epiphany ?

**Comment by codyfish** [comment]
In epiphany I have a similar problem: Reddits homepage doesn't load completely, I have to open a post in order to make it work. Then I can also scroll at the main page. Note that I do not always have this problem in gigagram, today it works flawlessly. Maybe reddit isn't suited for gigagram anyways as it isn't really a webapp and needs browser controls such as back and forward.

Love your app for WhatsApp as I do not always have to login. One question: Are cookies and similar stored per tab (thus is each tab in a container?)

**Comment by sonnyp** [comment]
For navigation controls, I started here https://github.com/sonnyp/gigagram/pull/14

> One question: Are cookies and similar stored per tab (thus is each tab in a container?)

Yes, every tab data (cookies, storage, cache, ...) is isolated.

**Comment by sonnyp** [comment]
Would navigation controls fix the original issue for you?

**Comment by sonnyp** [comment]
released 0.3.0 with navigation buttons, please test

**Comment by codyfish** [comment]
Nice, it works. Going back is really fast and feels better than in firefox. Thank you. Could you update the PKGBUILD in the aur? I had to install it manually because yay didn't recognize the new version. Your work is great, keep it up!

**Comment by sonnyp** [comment]
> I had to install it manually because yay didn't recognize the new version.

That's because the package was already built. When yay ask if you want to clean build just answer yes.
