### ISSUE TITLE
Various UI issues

### ISSUE THREAD

**Issue by bertob** [sonnyp/gigagram#20]
![image](https://user-images.githubusercontent.com/1908896/62160337-010f2b80-b314-11e9-9797-dc0354b85b9a.png)

These buttons need 6px margin between them, and the back/forward buttons should be on the left and joined, like in Epiphany:

![image](https://user-images.githubusercontent.com/1908896/62160769-091b9b00-b315-11e9-955d-b660646978d5.png)

![image](https://user-images.githubusercontent.com/1908896/62160480-64995900-b314-11e9-8f94-4d6ba36036ee.png)

It should be "Keyboard Shortcuts", and "About $APPNAME". Also, most likely Quit is not needed.

![image](https://user-images.githubusercontent.com/1908896/62160416-3d428c00-b314-11e9-80e6-c8381726d189.png)

There's no way to go back to the main menu view.

**Comment by sonnyp** [comment]
fixed in https://github.com/sonnyp/gigagram/commit/49ab31063c527dc4a38efe79c6f4b5e3ffd678c3, also added a menu separator before keyboard shortcuts like fractal

**Comment by sonnyp** [comment]
@bertob I wonder if it wasn't better to have the new tab icon to the far left so that it was directly at the same position as the back button when you clicked on it ?
