### ISSUE TITLE
[Feature request] `pass` integration

### ISSUE THREAD

**Issue by chri2** [sonnyp/gigagram#272]
It would be really nice to have some api to integrate a password safe like `pass`.

E.g. for firefox there's PassFF to integrate `pass`.

**Comment by sonnyp** [comment]
If you're going to request a feature, can you put a bit more effort into what, why and how?

**Comment by chri2** [comment]
You're right - sorry! I didn't put much thought into the idea - partly (lame excuse follows) because I do not know much about how something like what I'm thinking about could be integrated (easily).

I'll give it a try. I made a screenshot of what I referenced in Firefox - PassFF:

![2023-05-08_17-02-00-651141174](https://user-images.githubusercontent.com/15866990/236859466-8275458c-bf04-45cf-a0db-969214452543.png)

The extension puts a `P` in input fields it recognizes as username/password fields. Clicking that `P` gives a list of entries matching the host/domain of the site the fields are located at from the password manager [pass](https://www.passwordstore.org/).

I don't know whether a similar integration would be possible in tangram. The integration in firefox I like a lot and it is close to perfect with all the features it offers.

A version I could thing of that might be easier to integrate would work like this:

* tangram is started or a new tab is added and a login page is shown.
* tangram recognizes that there are input fields that the user might want to autofill
* tangram shows some icon somewhere for this page - just one to keep it simple and not clutter the gui. 
(Maybe a gesture would do also since the feature can be considered advanced and users interested in it would need to find out about it.)
*  If the user taps or clicks the icon or does the gesture an external program/script is called. Parameters given to script are
    *  the url of the page
    * the name/id of the different input fields in that page
* the script/program does whatever the user wants it to do to get the data to autofill the fields on that page
    * it returns nothing (fail or just no data - tangram wouldn't need to care?)
    * it returns a list of input field name/id and data pairs that tangram uses to fill the fields in that page

Without being a programer and knowing anything about the internal working of tangram I would hope that a solution similar to this
* would be not much code to integrate (let the external script/program do most of what maybe some users don't want anyway)
* would be open to integrate whatever data store users want to use as long as they'd be able to write a script or program as a bridge between tangram and the data storage

I'd give my best to integrate something for `pass`.

BTW: Thanks a lot for the great work on tangram! It really fills a gap and I'm about to use it as my email gui (snappymail as backend) and for my microblog.pub on the Librem5.

I really didn't want to give the impression I wouldn't value your work and time by being so unspecific.

**Comment by sonnyp** [comment]
The only integration I would consider for this is a freedesktop/xdg API.

Besides, it seems like a lot of work for little benefit. I type the password once per tab added.

Looks like a mobile client for pass would be more useful and work with any app.

**Comment by chri2** [comment]
> Looks like a mobile client for pass would be more useful and work with any app.

Yes, I'm looking into that. Someone made already one that works pretty good.

I don't know about the freedesktop/xdg API for that, but when I find time I'll read into it.

Just to explain my motivation:

* There are pages that expire your credentials independent of activity after some time
* Logging in on a mobile device is not done with the same speed and ease as on a full console

Yes, if it only me then it is not worth the work and additional code to avoid those one or two additional steps.

**Comment by sonnyp** [comment]
Let's revisit this when there is a standard API for credentials.
