### ISSUE TITLE
Problems running over waypipe

### ISSUE THREAD

**Issue by chri2** [sonnyp/gigagram#277]
Please include (to the best of your knowledge) the following information:

**Debugging Information**

WebKitGTK 2.40.1
GJS 1.76.0
Adw 1.3.2
GTK 4.10.3
GLib 2.76.2
libsoup 3.4.1
GStreamer 1.20.6

**Flatpak version**

`flatpak --version`

Flatpak 1.10.8

**Operating System**

PureOS Byzantium (Debian Bullseye)

**Desktop Environment**

`Notebook: Gnome 3.38.5 wayland, gnome-shell 3.38.6` → `waypipe -n ssh -R /tmp/socket-way:/tmp/socket-l5 Librem5` → `Librem5: Gnome 3.38.5 wayland, Phosh 0.27.0`

waypipe 0.8.6 (commit 033d0e7eb613f1ddfe104d07079a81b8d4e02dac)

I connected (actually to debug some other issue :facepalm:) from my notebook through ssh to my Librem5 phone using waypipe to get the tangram window from the phone on my notebook.

**Problem**

Starting Tangram everything seems to be normal and I get the following messages on the command line:

```
user@notebook$ waypipe -n ssh -R /tmp/socket-way:/tmp/socket-l5 Librem5
purism@pureos:~$ GDK_BACKEND=wayland flatpak run re.sonny.Tangram
Gjs-Message: 14:44:25.454: JS LOG: env: flatpak
Gjs-Message: 14:44:25.455: JS LOG: data_dir: /home/purism/.var/app/re.sonny.Tangram/data/Tangram
Gjs-Message: 14:44:25.455: JS LOG: cache_dir: /home/purism/.var/app/re.sonny.Tangram/cache/Tangram
Gjs-Message: 14:44:25.455: JS LOG: config_dir: /home/purism/.var/app/re.sonny.Tangram/config/Tangram
Gjs-Message: 14:44:25.455: JS LOG: applications_dir: /home/purism/.local/share/applications
Gjs-Message: 14:44:25.455: JS LOG: keyfile_settings_path: 
```

Tangrams window shows up on my notebook (forwarded over waypipe/ssh from the phone I logged into via ssh):

![2023-05-19_14-46-17-176777515](https://github.com/sonnyp/Tangram/assets/15866990/07685202-fc83-453e-a534-dc9910a5bb7e)

Clicking the `Go` button gives me the following message on the console:

```
(process:2): Gtk-WARNING **: 14:47:21.034: Failed to open display
```

And the gui output looks like this:

![2023-05-19_14-48-08-629737836](https://github.com/sonnyp/Tangram/assets/15866990/5252880e-2b07-4773-bc44-2d84cd548645)

Each time I enter a new address and click on `Add` the error message `(process:2): Gtk-WARNING **: 14:48:35.776: Failed to open display` is repeated and I end up with the same window content.

**Comment by sonnyp** [comment]
I'm afraid you'll have to dig yourself, I doubt a lot of people will run into this.

It looks related to WebkitGTK and sandbox. I suggest trying to reproduce with GNOME Web (flatpak)

**Comment by chri2** [comment]
Thanks, that is a good idea. I'll try that and report back if I find something out.

**Comment by chri2** [comment]
You were right, the problem is the same with gnome-web:

```
someuser@pureos:~$ waypipe -n ssh -R /tmp/socket-way:/tmp/socket-l5 l5h flatpak run org.gnome.Epiphany

(process:2): Gdk-WARNING **: 09:22:53.267: No such backend: *

(process:2): Gtk-WARNING **: 09:22:53.267: Failed to open display

(epiphany:2): epiphany-WARNING **: 09:22:53.279: Web process crashed

(process:2): Gdk-WARNING **: 09:22:54.024: No such backend: *

(process:2): Gtk-WARNING **: 09:22:54.024: Failed to open display

(epiphany:2): epiphany-WARNING **: 09:22:54.120: Web process crashed
```

**Comment by sonnyp** [comment]
I think your best chance is to report the issue to waypipe.
