### ISSUE TITLE
Snap package ready

### ISSUE THREAD

**Issue by soumyaDghosh** [sonnyp/gigagram#281]
Hi, your package is ready as a snap. Would you like to publish it in the snap store? Also someone has taken the name in the store, so, your intervension would also be needed to get the name may be it for you or for us. Thanks.

**Comment by sonnyp** [comment]
Thank you for your interest in Tangram, I am not interested in publishing on the Snap store.
Please do not publish Tangram in the snap store.

**Comment by soumyaDghosh** [comment]
This is to make `Tangram` available for all the Ubuntu users who don't use/like flatpaks. If you don't want, I would like to publish it as an unofficial package.

**Comment by sonnyp** [comment]
I know what it is for.

>  If you don't want, I would like to publish it as an unofficial package.

I thought I was clear: Please do not publish Tangram in the snap store.

https://floss.social/@sonny/110482675308591314

**Comment by sonnyp** [comment]
I explained my decision here https://floss.social/@sonny/110559016057505402

**Comment by soumyaDghosh** [comment]
> I explained my decision here https://floss.social/@sonny/110559016057505402

I have seen it, and TBH, it's a very unprofessional, biased opinion which is based completely on half knowledge. There are snaps maintained by me which are now official, and gets update even before the flatpak(flatpak servers take time for an update to be pushed), like Tube Converter, Denaro, Tagger, Graphs. 

>People are starting to offer (and insist) to publish my apps on the Snap Store.

I am not insisting you to publish it. I can publish it, maintain it properly just like I am maintaining 25+ other snaps and two sdks for almost 6 months now. But, just like in every other case, I am here again asking you if you would like to have it or not. 

>Snaps don't appear to get updated. “Publish and forget”.

A very biased, opinionated, false narrative based on half knowledge.

>Every minute spent on Snap is a minute of development lost. I organize events, maintain 10 apps, contribute, mentor students, … on my (unpaid) free time. I really don't have time for this.

Again, I will try my best, so that no one comes to your repo to ask for help. If anyone comes, you simply don't reply them, say them the truth, that this package, is maintained unofficially without your will. So, you're not ready to maintain it. 

All my above opinions are contradictory to you, still I respect your work, you as person. But, opinions given by you in the social media page, is actually a half-baked knowledge and very much based on assumptions. Specifically this one,

>Bottles and GNOME Builder also don't support non flatpak distributions of their apps.

Snaps have many reasons to hate. Not only you, many others do the same. But, what you can't disagree is it still has more user base than any other package format.

Thanks for your explanations. But, I'll try my best to have this app as a snap, maintained and properly supported, with updates just on time or before flatpaks. 

## Sorry again, if I have hurt you in any way.

**Comment by sonnyp** [comment]
> There are snaps maintained by me which are now official

I'm sure you do a great job, this isn't directed at you.

> I am not insisting you to publish it.

Asking multiple times is insisting.

> A very biased, opinionated, false narrative based on half knowledge.

Please at least tell me what I am wrong about?

I got this is from a post you published and the discussion that followed.

https://forum.snapcraft.io/t/snaps-are-getting-cornered/33766

> very much based on assumptions. Specifically this one,

The statement “Bottles and GNOME Builder also don't support non flatpak distributions of their apps.” isn't an assumption, it's a fact. Feel free to verify it for yourself. 

>  But, what you can't disagree is it still has more user base than any other package format.

Possibly, but as a FLOSS developer, this isn't very relevant to me, specially when it means more work without any perspective for monetization (which seems to have been abandoned by Canonical).

> Sorry again, if I have hurt you in any way.

Not at all.

**Comment by soumyaDghosh** [comment]
> The statement “Bottles and GNOME Builder also don't support non flatpak distributions of their apps.” isn't an assumption, it's a fact. Feel free to verify it for yourself.

Don't worry, you'll find an official snap of `bottles` within some months. :wink: 


> Please at least tell me what I am wrong about?

Scenario of snaps have changed now, surely big apps like `gimp`, `obs-studio` aren't still properly updated yet, but small apps are. There are also automated tools coming up for this thing. 



> https://forum.snapcraft.io/t/snaps-are-getting-cornered/33766

Sure, that's a constructive criticism from me. `Krita` and `Evince` is now supported properly. I, myself, am working on `OBS` and `Gimp` hopefully make them fully work asap. Also, the documentations have also improved. I also fixed the irritating `webkitgtk problem`, where there was no easy way to build snaps based on `Webkitgtk-6` and there comes the `webkitgtk-6-gnome-2204` content snap, resulting your app work as a snap. That's why I am so sure about its reliability. Just let me prove it by allowing me to publish it in the store as an **UNOFFICIAL** app. Thanks again for your cooperation.
