### ISSUE TITLE
some websites freeze and become unresponsive when minimized

### ISSUE THREAD

**Issue by sbe-arg** [sonnyp/gigagram#284]
Noticed that when using whatsapp web regardless time in foreground. Once minimized or app focus changed to another web app. once the original web app is back to focus is frozen and completly urresponsive. Only restarting/recycling the webapp or reopening tangram makes the tab in focus work again.

Similar behaviour observed with Youtube music (when not playing music). 
Switching web apps make some of the inactive apps to freeze. 
I'm out of ideas really. 

---

Please include (to the best of your knowledge) the following information:

**Debugging info**

```
WebKitGTK 2.40.4
GJS 1.76.2
Adw 1.3.3
GTK 4.10.4
GLib 2.76.3
libsoup 3.4.2
GStreamer 1.20.6
```
```
flatpak info re.sonny.Tangram

Tangram - Browser for your pinned tabs

          ID: re.sonny.Tangram
         Ref: app/re.sonny.Tangram/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.0
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 652.8 kB
     Runtime: org.gnome.Platform/x86_64/44
         Sdk: org.gnome.Sdk/x86_64/44

      Commit: 048515477316aaafd9934f533c8cf855240a13d1c1a4c0f66f5197ea5b1253a4
      Parent: e4a4fd76a4032685fe8dabfa6a53cebbe5eb8fd1673b42decdfe9c5413744240
     Subject: v3.0 (#28) (2372e661)
        Date: 2023-04-29 12:12:01 +0000
```

flatpak run shows no errors of any form

**Flatpak version**

Flatpak 1.15.4

**Operating System**

Fedora 38

**Desktop Environment**

GNOME Shell 44.3 Wayland

**Comment by philn** [comment]
What's your GPU?

**Comment by sbe-arg** [comment]
Ill re test this and update.

But I'm using ubuntu 22 on an xps 13 plus (intel gpu) nowadays

**Comment by sbe-arg** [comment]
seems fixed now on fedora 39
