### ISSUE TITLE
When a video is in full-screen, the tab bar is still visible

### ISSUE THREAD

**Issue by cyruseuros** [sonnyp/gigagram#287]
Title

**Debugging Information**
WebKitGTK 2.42.1
GJS 1.76.2
Adw 1.3.5
GTK 4.10.5
GLib 2.76.5
libsoup 3.4.3
GStreamer 1.20.7

**Flatpak version**
1.15.4

**Operating System**
Arch Linux

**Desktop Environment**
GNOME Shell 45 Wayland

**Comment by philn** [comment]
Duplicate of #261 ?

**Comment by sonnyp** [comment]
Duplicate of https://github.com/sonnyp/Tangram/issues/261
