### ISSUE TITLE
FR: Implement more sandbox portals

### ISSUE THREAD

**Issue by tjapro** [sonnyp/gigagram#299]
Hello!

Tpday, I tried to send a voice message through Tangram, and it seems there isn't any implementation of that at the time.  
Also, I went to Flatseal to see if there was some permissions that I could activate but there isn't or are not implemented.

So, there isn't a way to access microphone in Tangram.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/178
