### ISSUE TITLE
BUG: Many emojies in WhatsApp don't appear

### ISSUE THREAD

**Issue by kbdragon** [sonnyp/gigagram#300]
Reaction emojis randomly don't load in WhatsApp Web:

![Screenshot from 2024-05-09 12-23-15](https://github.com/sonnyp/Tangram/assets/113253861/dc24af53-c270-4ac7-814c-76be96bc4fdc)

I tested Telegram Web, and all emojis appear as expected.

---

**Debugging Information**

WebKitGTK 2.44.1
GJS 1.78.5
Adw 1.4.4
GTK 4.12.5
GLib 2.78.4
libsoup 3.4.4
GStreamer 1.22.11

**Flatpak version**

Flatpak 1.15.8

**Operating System**

OpenSuse TumbleWeed 

**Desktop Environment**

GNOME Shell 46 Wayland

**Comment by philn** [comment]
Can you check if this happens with Epiphany too? If so, it might be a WebKitGTK bug.

**Comment by kbdragon** [comment]
@philn 
Just tested on Epiphany, and you're right - it's a webkit bug. I'll try to submit a report upstream.

**Comment by philn** [comment]
Upstream bug is https://bugs.webkit.org/show_bug.cgi?id=274007 so let's close this.
