### ISSUE TITLE
FR: Hibernate tabs

### ISSUE THREAD

**Issue by kbdragon** [sonnyp/gigagram#301]
There are services we use regularly, and there are services we only occasionally need to be active. It would be great if we could add tab / service hibernation (unloading) to preserve resources. This would be especially useful on laptops with limited battery.

**Comment by BritishTeapot** [comment]
I am all for this feature too. Because most web apps are quite resource-heavy, hibernation feature is an absolute must for an app that is made *specifically to manage web apps*.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/194
