### ISSUE TITLE
Bug (or FR?): TYangram doesn't remember tab order

### ISSUE THREAD

**Issue by kbdragon** [sonnyp/gigagram#302]
I'm trying to rearrange the order of the tabs / services, and I can do that in the session. But when existing and reopening the app, all tabs revert to the previous order.

Expected behavior: if I can rearrange them, Tangram should remember the new position.

---

Please include (to the best of your knowledge) the following information:

**Debugging Information**

WebKitGTK 2.44.2
GJS 1.80.2
Adw 1.5.1
GTK 4.14.4
GLib 2.80.2
libsoup 3.4.4
GStreamer 1.22.12

**Flatpak version**

Flatpak 1.15.8

**Operating System**

OpenSuse Tumbleweed

**Desktop Environment**

GNOME Shell 46 Wayland

**Comment by birdhimself** [comment]
Can confirm.

WebKitGTK 2.44.2
GJS 1.80.2
Adw 1.5.1
GTK 4.14.4
GLib 2.80.2
libsoup 3.4.4
GStreamer 1.22.12

Fedora 40, Flatpak 1.15.8, GNOME 46 Wayland

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/issues/215
