### ISSUE TITLE
Keyboard controls

### ISSUE THREAD

**Issue by mustafapc19** [sonnyp/gigagram#6]
I suggesting 
1 - keyboard shortcuts for increasing/decreasing overall size of text and gfx stuff .
2 - If the app is going in the direction of tabs, then keyboard shortcuts for tab switching.
3 - Removing title bar in favour of header bar.

Another suggestion is to allow users to drag out the tab to create a new window. Should I create a new issue for this?

I can help but I don't know much about gjs and gtk. Have a little idea though.

**Comment by sonnyp** [comment]
I started working on the header bar. What would you like it to do/have? 

> 1 - keyboard shortcuts for increasing/decreasing overall size of text and gfx stuff .
> 2 - If the app is going in the direction of tabs, then keyboard shortcuts for tab switching.

I'll add key bindings for tab switching, I will let you know and you can do the additional ones you want/need by looking at the code.

> Another suggestion is to allow users to drag out the tab to create a new window. Should I create a new issue for this?

I have something similar on my radar, I'd like to allow users to create new apps with their own icons, name, tabs. (basically simple .desktop files).  Would that work for you?

**Comment by mustafapc19** [comment]
> I started working on the header bar. What would you like it to do/have?

I am interested to help. But I am kinda busy for like 4 days. I am looking into the code though.

> I have something similar on my radar, I'd like to allow users to create new apps with their own icons, name, tabs. (basically simple .desktop files). Would that work for you?

Best idea for the time being is to create a detach button on the header bar which will remove the current tab and create the separate app(.desktop file). But will also have to include a way to destroying the app though.

**Comment by sonnyp** [comment]
> Best idea for the time being is to create a detach button on the header bar which will remove the current tab and create the separate app(.desktop file). But will also have to include a way to destroying the app though.

No need for a detach button, tabs can be detached by drag'n drop like in GNOME Web/epiphany. I'm thinking allowing the user to do that and when a tab is detached open a dialog window ask for app name/icon/...

**Comment by mustafapc19** [comment]
Yeah. But detaching is good but I feel it might become one of this hidden features. Having a detach button will make the users know about this feature. I am on board with the drag'n drop feature.

**Comment by sonnyp** [comment]
Head bar is now in master :)

**Comment by sonnyp** [comment]
I added a menu button to the header bar that allows to change tabs position

**Comment by sonnyp** [comment]
For future reference, "Standard Keyboard Shortcuts" on https://developer.gnome.org/hig/stable/tabs.html.en

**Comment by sonnyp** [comment]
https://github.com/sonnyp/gigagram/pull/18

**Comment by sonnyp** [comment]
There are no keyboard shortcuts for zoom but it should be easy to add if you are interested

see https://gjs-docs.gnome.org/webkit240~4.0_api/webkit2.webview#method-set_zoom_level
